export const NURSING_MOCK_DATA = {
  activeDispatch: {
    patientName: 'Meenakshi Raman',
    age: 72,
    visitType: 'Post-Op Wound Care',
    address: 'Block A, 15th Main Rd, Anna Nagar, Chennai',
    status: 'urgent',
    vitals: {
      spO2: { value: 96, status: 'normal' },
      heartRate: { value: 88, status: 'normal' },
      bp: { value: '140/90', status: 'warning' },
    },
  },
  careQueue: [
    {
      id: 'Q-1001',
      patientName: 'K. Balakrishnan',
      initials: 'KB',
      age: 68,
      visitType: 'IV Fluid Admin',
      address: '2nd Street, T. Nagar',
      status: 'Accepted',
      urgent: false,
    },
    {
      id: 'Q-1002',
      patientName: 'Lakshmi N.',
      initials: 'LN',
      age: 81,
      visitType: 'Catheter Change',
      address: 'Dhandeeswaram, Velachery',
      status: 'Pending',
      urgent: true,
    },
    {
      id: 'Q-1003',
      patientName: 'Suresh Kumar',
      initials: 'SK',
      age: 55,
      visitType: 'Post-Stroke Physio',
      address: 'LB Road, Adyar',
      status: 'Completed',
      urgent: false,
    },
    {
      id: 'Q-1004',
      patientName: 'Anita V.',
      initials: 'AV',
      age: 42,
      visitType: 'Chemo Port Flush',
      address: 'Indira Nagar, Adyar',
      status: 'Accepted',
      urgent: false,
    },
  ],
  weeklyPerformance: [
    { day: 'Mon', visits: 5, responseTime: 25 },
    { day: 'Tue', visits: 7, responseTime: 22 },
    { day: 'Wed', visits: 4, responseTime: 30 },
    { day: 'Thu', visits: 6, responseTime: 20 },
    { day: 'Fri', visits: 8, responseTime: 18 },
    { day: 'Sat', visits: 3, responseTime: 35 },
    { day: 'Sun', visits: 2, responseTime: 40 },
  ],
  kitStock: [
    { item: 'Sterile Gauze Pads', status: 'ok', level: 80 },
    { item: 'IV Cannulas (20G)', status: 'low', level: 15 },
    { item: 'Saline Solution (500ml)', status: 'ok', level: 60 },
    { item: 'Surgical Tape', status: 'ok', level: 75 },
    { item: 'Lidocaine Spray', status: 'low', level: 10 },
  ],
  initialHandoffNotes: [
    {
      id: 1,
      timestamp: '10:30 AM',
      note: 'Checked Meenakshi ammal wound. Healing well, no sign of infection. Applied fresh dressing.',
      author: 'Nurse Sarah',
    },
    {
      id: 2,
      timestamp: '08:45 AM',
      note: 'Mr. Balakrishnan BP was slightly elevated (145/95). Informed primary physician. Will monitor next visit.',
      author: 'Nurse Preeti',
    },
  ],
  notifications: [
    {
      id: 1,
      title: 'Emergency Request',
      desc: 'New SOS request from Velachery. Requires immediate dispatch.',
      time: '2 mins ago',
      unread: true,
      type: 'urgent',
    },
    {
      id: 2,
      title: 'Stock Alert',
      desc: 'IV Cannulas running critically low in Kit A.',
      time: '1 hr ago',
      unread: true,
      type: 'warning',
    },
    {
      id: 3,
      title: 'Visit Completed',
      desc: 'Suresh Kumar care chart updated successfully.',
      time: '3 hrs ago',
      unread: false,
      type: 'success',
    },
  ],
};
